sy on
set nu
set cursorline					"Highlight current line"
set title

set ts=4
set autoindent
set smartindent

set hlsearch
set smartcase					"No CamelCase search"
set incsearch					"Incremental search"

set background=dark
colorscheme hybrid

set formatoptions+=r			"Autocomment if previous line is a comment"
