alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"
alias tar="tar -v"
alias chmod="chmod -v"
alias dd="dd status=progress"
alias files="nautilus"
alias ls='ls --color=auto'
alias grep='grep -H -n --color=auto'
alias nodemon="nodemon --harmony"
alias gcc="gcc -Wall -Wextra -Werror"
alias diff="diff --color=always"
alias cal="cal -Y"
alias bc="bc -l"
alias objdump="objdump -M intel"
alias xclip="xclip -selection clipboard"
