autoclip: false
autoimport: true
cliptimeout: 10
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /home/user/.local/share/gopass/stores/root
safecontent: true
mounts: {}
